version: "3"
services:
  master:
    container_name: master
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: slave01
    image: jenkinsci/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJHeXIN0Io19lEVwaOf5Cyh4g9hzwXyNRS6wZ7rvhfhL2xiidxkhPZfmxpF2HR3PiKdiF1j5jGYH/Z8P8oMVR7uCHK/8uYKVFwtCCcf9Bi7ERmHsluwiIpbkE3D4NZCONbfnVzVhOS5G+/I9ahZfZc1vs7PHvBdr5edsTq8ubK1Dm/PcFtCXATVrCp8LW9K5ENCibOwq1W/1cA7pBzxxKavbd159LwlPmpmlWzELYfOgBG9Atyt+2HqqhYx61tmVziNh3XpFPZjMNO8WrXV9egp0IQTra/RmF/nFtCNEFaBL+IrNJ4RRHN3pE3fJE2PAK1Ahdne25SufUNa0S4etaz
